##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
# https://github.com/CollectionBuilder/collectionbuilder-csv
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://swat-ds.github.io/material-culture
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /material-culture
# location of code, the full url to your github repository
source-code: https://github.com/swat-ds/material-culture/

##########
# SITE SETTINGS
#
# title of site appears in banner
title: From Local to Global - Consumption and the Quaker Body
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Exhibition curated by the students of ARTH083 - Object, Media, Matter - Introduction to Material Culture and Material Histories, Fall 2025, Swarthmore College
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Site created for the class ARTH083 taught by professor Susan Eberhard"
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
keywords: swat; quaker; collection; material;
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: swat-ds

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the CSV file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: artifacts
# Note, this file will be refreshed from the source Google Sheets
# page generation settings [optional!]
# [optional: only used if you need to tweak CB defaults or generate from more than one data file]
page_gen:
  - data: 'artifacts'   

##########
# Site/Organization Branding 
#   Enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#   To remove the branding, comment out these values, or delete them. 
#
organization-name: "Swarthmore College"
organization-link: https://liblab.swarthmore.edu/
# organization-logo-banner: 
# organization-logo-nav: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md, utilities/]
# compress CSS output
sass:
  style: compressed
